language: node_js

node_js: --lts

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - git config --global user.name 'JounQin'
  - git config --global user.email 'admin@1stg.me'

script:
  - yarn lint
  - yarn build
  - yarn build-storybook

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch: master
  - provider: pages
    email: admin@1stg.me
    name: JounQin
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    allow_empty_commit: false
    local_dir: storybook-static
    on:
      branch: master
